{
    "apiVersion":"2.1",
    "data":{
        "updated":"2014-04-08T14:59:51.728Z",
        "totalItems":49,
        "startIndex":1,
        "itemsPerPage":25,
        "items":[
        {
            "id":"mY29wEhx77o",
            "uploaded":"2014-04-07T17:37:40.000Z",
            "updated":"2014-04-07T21:35:58.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"RETO MORNINGLORY",
            "description":"RETO MORNINGLORY",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/mY29wEhx77o/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/mY29wEhx77o/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=mY29wEhx77o&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=mY29wEhx77o"
            },
            "content":{
                "5":"http://www.youtube.com/v/mY29wEhx77o?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r6---sn-4g57kuee.c.youtube.com/CigLENy73wIaHwm673FIwL2NmRMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r6---sn-4g57kuee.c.youtube.com/CigLENy73wIaHwm673FIwL2NmRMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":392,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"6",
            "ratingCount":6,
            "viewCount":138,
            "favoriteCount":0,
            "commentCount":0,
            "restrictions":[
            {
                "type":"country",
                "relationship":"deny",
                "countries":"DE"
            }
            ],
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"hcmr_2K_Mpc",
            "uploaded":"2014-04-01T08:53:30.000Z",
            "updated":"2014-04-03T20:04:55.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Programa entrenos Juanjo Martín PILOTO",
            "description":"",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/hcmr_2K_Mpc/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/hcmr_2K_Mpc/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=hcmr_2K_Mpc&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=hcmr_2K_Mpc"
            },
            "content":{
                "5":"http://www.youtube.com/v/hcmr_2K_Mpc?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r5---sn-4g57kuek.c.youtube.com/CigLENy73wIaHwmXMr9i_6vJhRMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r5---sn-4g57kuek.c.youtube.com/CigLENy73wIaHwmXMr9i_6vJhRMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":163,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"13",
            "ratingCount":13,
            "viewCount":1021,
            "favoriteCount":0,
            "commentCount":1,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"lwTuxjOcyiM",
            "uploaded":"2014-03-28T18:17:16.000Z",
            "updated":"2014-03-31T17:26:36.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Sentadilla a una pierna con salto lateral en TRX",
            "description":"Sentadilla a una pierna con salto lateral con TRX",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/lwTuxjOcyiM/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/lwTuxjOcyiM/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=lwTuxjOcyiM&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=lwTuxjOcyiM"
            },
            "content":{
                "5":"http://www.youtube.com/v/lwTuxjOcyiM?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r6---sn-4g57kuee.c.youtube.com/CigLENy73wIaHwkjypwzxu4ElxMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r6---sn-4g57kuee.c.youtube.com/CigLENy73wIaHwkjypwzxu4ElxMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":24,
            "aspectRatio":"widescreen",
            "viewCount":127,
            "favoriteCount":0,
            "commentCount":1,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"BdlGyR4N3W4",
            "uploaded":"2014-03-04T10:34:18.000Z",
            "updated":"2014-03-28T18:21:51.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Saltos al cajón o banco",
            "description":"Ejerció para trabajar la potencia del tren inferior, el CARDIO y la coordinación.",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/BdlGyR4N3W4/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/BdlGyR4N3W4/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=BdlGyR4N3W4&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=BdlGyR4N3W4"
            },
            "content":{
                "5":"http://www.youtube.com/v/BdlGyR4N3W4?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r8---sn-4g57kuek.c.youtube.com/CigLENy73wIaHwlu3Q0eyUbZBRMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r8---sn-4g57kuek.c.youtube.com/CigLENy73wIaHwlu3Q0eyUbZBRMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":17,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"1",
            "ratingCount":1,
            "viewCount":136,
            "favoriteCount":0,
            "commentCount":1,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"5D7mmjK0XLk",
            "uploaded":"2014-02-28T11:38:28.000Z",
            "updated":"2014-03-28T18:22:47.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Fondos inclinados con palmada",
            "description":"Fondos inclinados con palmada",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/5D7mmjK0XLk/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/5D7mmjK0XLk/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=5D7mmjK0XLk&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=5D7mmjK0XLk"
            },
            "content":{
                "5":"http://www.youtube.com/v/5D7mmjK0XLk?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r6---sn-4g57kuez.c.youtube.com/CigLENy73wIaHwm5XLQymuY-5BMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r6---sn-4g57kuez.c.youtube.com/CigLENy73wIaHwm5XLQymuY-5BMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":15,
            "aspectRatio":"widescreen",
            "viewCount":99,
            "favoriteCount":0,
            "commentCount":1,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"9QLj4SZB1hc",
            "uploaded":"2014-02-21T09:53:54.000Z",
            "updated":"2014-03-28T18:20:47.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Salto al cajón con peso",
            "description":"Salto al cajón con peso buen ejercicio funcional.",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/9QLj4SZB1hc/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/9QLj4SZB1hc/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=9QLj4SZB1hc&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=9QLj4SZB1hc"
            },
            "content":{
                "5":"http://www.youtube.com/v/9QLj4SZB1hc?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r1---sn-4g57kuel.c.youtube.com/CigLENy73wIaHwkX1kEm4eMC9RMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r1---sn-4g57kuel.c.youtube.com/CigLENy73wIaHwkX1kEm4eMC9RMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":16,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"1",
            "ratingCount":1,
            "viewCount":201,
            "favoriteCount":0,
            "commentCount":2,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"gy24jPUX_XI",
            "uploaded":"2014-02-21T09:49:48.000Z",
            "updated":"2014-03-28T18:19:15.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Ejercicio de pecho en TRX",
            "description":"Ejercicio de pecho con TRX excelente porque involucramos el core, piernas, gemelos, equilibro, coordinación, es muy completo",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/gy24jPUX_XI/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/gy24jPUX_XI/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=gy24jPUX_XI&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=gy24jPUX_XI"
            },
            "content":{
                "5":"http://www.youtube.com/v/gy24jPUX_XI?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r7---sn-4g57kued.c.youtube.com/CigLENy73wIaHwly_Rf1jLgtgxMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r7---sn-4g57kued.c.youtube.com/CigLENy73wIaHwly_Rf1jLgtgxMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":16,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"1",
            "ratingCount":1,
            "viewCount":133,
            "favoriteCount":0,
            "commentCount":1,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"ETqH5FMDhpk",
            "uploaded":"2014-02-21T09:41:01.000Z",
            "updated":"2014-03-28T18:17:30.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Ejercicio para #oblicuo #serratos #dorsal #hombro con goma",
            "description":"Ejerció funcional excelente para trabajar los oblicuos, serratos, dorsal y hombro.",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/ETqH5FMDhpk/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/ETqH5FMDhpk/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=ETqH5FMDhpk&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=ETqH5FMDhpk"
            },
            "content":{
                "5":"http://www.youtube.com/v/ETqH5FMDhpk?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r3---sn-4g57kuek.c.youtube.com/CigLENy73wIaHwmZhgNT5Ic6ERMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r3---sn-4g57kuek.c.youtube.com/CigLENy73wIaHwmZhgNT5Ic6ERMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":16,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"1",
            "ratingCount":1,
            "viewCount":286,
            "favoriteCount":0,
            "commentCount":1,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"3EONTC0E_3o",
            "uploaded":"2014-02-13T11:32:50.000Z",
            "updated":"2014-03-28T18:25:18.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Entrenamiento funcional cross&fitness zancada con apertura para pecho con gomas",
            "description":"Aperturas de pecho con gomas",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/3EONTC0E_3o/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/3EONTC0E_3o/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=3EONTC0E_3o&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=3EONTC0E_3o"
            },
            "content":{
                "5":"http://www.youtube.com/v/3EONTC0E_3o?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r1---sn-4g57kuel.c.youtube.com/CigLENy73wIaHwl6_wQtTI1D3BMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r1---sn-4g57kuel.c.youtube.com/CigLENy73wIaHwl6_wQtTI1D3BMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":15,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"2",
            "ratingCount":2,
            "viewCount":201,
            "favoriteCount":0,
            "commentCount":2,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"NX8K_yjehpk",
            "uploaded":"2014-02-11T13:14:33.000Z",
            "updated":"2014-03-02T15:50:56.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"ABS con TRX",
            "description":"Abdominales en TRX trabajamos todo el recto abdominal.",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/NX8K_yjehpk/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/NX8K_yjehpk/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=NX8K_yjehpk&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=NX8K_yjehpk"
            },
            "content":{
                "5":"http://www.youtube.com/v/NX8K_yjehpk?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r5---sn-4g57kuek.c.youtube.com/CigLENy73wIaHwmZht4o_wp_NRMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r5---sn-4g57kuek.c.youtube.com/CigLENy73wIaHwmZht4o_wp_NRMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":16,
            "rating":5.0,
            "likeCount":"2",
            "ratingCount":2,
            "viewCount":330,
            "favoriteCount":0,
            "commentCount":3,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"_GVczZ9gZ0M",
            "uploaded":"2014-02-10T12:10:13.000Z",
            "updated":"2014-02-19T21:06:08.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Crossfit",
            "description":"Entrenamiento de crossfit de fuerza y resistencia",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/_GVczZ9gZ0M/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/_GVczZ9gZ0M/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=_GVczZ9gZ0M&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=_GVczZ9gZ0M"
            },
            "content":{
                "5":"http://www.youtube.com/v/_GVczZ9gZ0M?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r4---sn-4g57kuez.c.youtube.com/CigLENy73wIaHwlDZ2CfzVxl_BMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r4---sn-4g57kuez.c.youtube.com/CigLENy73wIaHwlDZ2CfzVxl_BMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":16,
            "rating":5.0,
            "likeCount":"2",
            "ratingCount":2,
            "viewCount":548,
            "favoriteCount":0,
            "commentCount":1,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"N_hd0p0Et_c",
            "uploaded":"2014-02-02T17:00:03.000Z",
            "updated":"2014-02-05T15:32:16.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"entrenamiento crossfit",
            "description":"crossfit cardio",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/N_hd0p0Et_c/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/N_hd0p0Et_c/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=N_hd0p0Et_c&feature=youtube_gdata_player"
            },
            "content":{
                "5":"http://www.youtube.com/v/N_hd0p0Et_c?version=3&f=user_uploads&app=youtube_gdata"
            },
            "duration":270,
            "aspectRatio":"widescreen",
            "geoCoordinates":{
                "latitude":40.44123,
                "longitude":-3.69326
            },
            "rating":5.0,
            "likeCount":"1",
            "ratingCount":1,
            "viewCount":412,
            "favoriteCount":0,
            "commentCount":3,
            "status":{
                "value":"restricted",
                "reason":"limitedSyndication"
            },
            "accessControl":{
                "comment":"moderated",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"denied"
            }
        },
        {
            "id":"6rDAdyWBfVE",
            "uploaded":"2014-01-17T15:34:17.000Z",
            "updated":"2014-03-28T18:25:38.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"ENTRENAMIENTO CROSS&FITNESS FUERZA",
            "description":"EJERCICIOS PARA POTENCIAR LOS GRANDES MUSCULOS DEL CUERPO Y GANAR MASA MUSCULAR",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/6rDAdyWBfVE/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/6rDAdyWBfVE/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=6rDAdyWBfVE&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=6rDAdyWBfVE"
            },
            "content":{
                "5":"http://www.youtube.com/v/6rDAdyWBfVE?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r1---sn-4g57kuel.c.youtube.com/CigLENy73wIaHwlRfYEld8Cw6hMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r1---sn-4g57kuel.c.youtube.com/CigLENy73wIaHwlRfYEld8Cw6hMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":16,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"1",
            "ratingCount":1,
            "viewCount":614,
            "favoriteCount":0,
            "commentCount":2,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"tzMBkATcZ5I",
            "uploaded":"2014-01-16T22:07:41.000Z",
            "updated":"2014-04-01T17:04:49.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Entrenamiento de crossfit de fuerza y resistencia principiantes",
            "description":"Entrenamiento de crossfit para iniciados, fuerza y resistencia.",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/tzMBkATcZ5I/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/tzMBkATcZ5I/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=tzMBkATcZ5I&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=tzMBkATcZ5I"
            },
            "content":{
                "5":"http://www.youtube.com/v/tzMBkATcZ5I?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r8---sn-4g57kue6.c.youtube.com/CigLENy73wIaHwmSZ9wEkAEztxMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r8---sn-4g57kue6.c.youtube.com/CigLENy73wIaHwmSZ9wEkAEztxMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":289,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"11",
            "ratingCount":11,
            "viewCount":3951,
            "favoriteCount":0,
            "commentCount":4,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"SwNBUqXOBYo",
            "uploaded":"2014-01-15T12:20:26.000Z",
            "updated":"2014-02-13T11:33:15.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Cross&fitness circuito de CARDIO intenso Juanjo Martín",
            "description":"entrenamiento de crossfit mas enfocado al cardio",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/SwNBUqXOBYo/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/SwNBUqXOBYo/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=SwNBUqXOBYo&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=SwNBUqXOBYo"
            },
            "content":{
                "5":"http://www.youtube.com/v/SwNBUqXOBYo?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r5---sn-4g57kuee.c.youtube.com/CigLENy73wIaHwmKBc6lUkEDSxMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r5---sn-4g57kuee.c.youtube.com/CigLENy73wIaHwmKBc6lUkEDSxMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":258,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"4",
            "ratingCount":4,
            "viewCount":976,
            "favoriteCount":0,
            "commentCount":1,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"JEAqt1NNZhA",
            "uploaded":"2013-12-17T10:50:35.000Z",
            "updated":"2014-01-16T22:09:32.000Z",
            "uploader":"entrenosjuanjo",
            "category":"People",
            "title":"Sentadilla con mancuerna, piernas abiertas.",
            "description":"sentadilla profunda con mancuerna",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/JEAqt1NNZhA/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/JEAqt1NNZhA/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=JEAqt1NNZhA&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=JEAqt1NNZhA"
            },
            "content":{
                "5":"http://www.youtube.com/v/JEAqt1NNZhA?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r3---sn-4g57kuel.c.youtube.com/CigLENy73wIaHwkQZk1TtypAJBMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r3---sn-4g57kuel.c.youtube.com/CigLENy73wIaHwkQZk1TtypAJBMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":61,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"3",
            "ratingCount":3,
            "viewCount":1717,
            "favoriteCount":0,
            "commentCount":1,
            "restrictions":[
            {
                "type":"country",
                "relationship":"deny",
                "countries":"DE"
            }
            ],
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"sBMKToc8BF0",
            "uploaded":"2013-12-17T00:34:58.000Z",
            "updated":"2014-01-16T22:11:46.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"Press de banca.",
            "description":"ejercicio basico de pecho, con las rodillas elevadas para apoyar el dorsal y mantener el abdomen en tensión",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/sBMKToc8BF0/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/sBMKToc8BF0/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=sBMKToc8BF0&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=sBMKToc8BF0"
            },
            "content":{
                "5":"http://www.youtube.com/v/sBMKToc8BF0?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r4---sn-4g57kuee.c.youtube.com/CigLENy73wIaHwldBDyHTgoTsBMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r4---sn-4g57kuee.c.youtube.com/CigLENy73wIaHwldBDyHTgoTsBMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":44,
            "aspectRatio":"widescreen",
            "rating":3.0,
            "likeCount":"1",
            "ratingCount":2,
            "viewCount":253,
            "favoriteCount":0,
            "commentCount":1,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"AmkfO3-ejJI",
            "uploaded":"2013-12-17T00:33:24.000Z",
            "updated":"2013-12-23T15:25:31.000Z",
            "uploader":"entrenosjuanjo",
            "category":"People",
            "title":"Subida al banco a una pierna.",
            "description":"a través de YouTube Capture",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/AmkfO3-ejJI/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/AmkfO3-ejJI/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=AmkfO3-ejJI&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=AmkfO3-ejJI"
            },
            "content":{
                "5":"http://www.youtube.com/v/AmkfO3-ejJI?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r7---sn-4g57kuel.c.youtube.com/CigLENy73wIaHwmSjJ5_Ox9pAhMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r7---sn-4g57kuel.c.youtube.com/CigLENy73wIaHwmSjJ5_Ox9pAhMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":62,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"1",
            "ratingCount":1,
            "viewCount":387,
            "favoriteCount":0,
            "commentCount":0,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"7rNZXleUN2E",
            "uploaded":"2013-12-17T00:21:59.000Z",
            "updated":"2013-12-17T00:31:33.000Z",
            "uploader":"entrenosjuanjo",
            "category":"People",
            "title":"Balanceos con disco.",
            "description":"a través de YouTube Capture",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/7rNZXleUN2E/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/7rNZXleUN2E/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=7rNZXleUN2E&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=7rNZXleUN2E"
            },
            "content":{
                "5":"http://www.youtube.com/v/7rNZXleUN2E?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r1---sn-4g57kuee.c.youtube.com/CigLENy73wIaHwlhN5RXXlmz7hMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r1---sn-4g57kuee.c.youtube.com/CigLENy73wIaHwlhN5RXXlmz7hMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":44,
            "aspectRatio":"widescreen",
            "viewCount":402,
            "favoriteCount":0,
            "commentCount":0,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"Mv3h4vdJ0DY",
            "uploaded":"2013-12-17T00:18:40.000Z",
            "updated":"2014-01-16T22:14:45.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"ABS elevamiento de piernas al techo.",
            "description":"ejercicio intenso para el abdomen.",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/Mv3h4vdJ0DY/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/Mv3h4vdJ0DY/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=Mv3h4vdJ0DY&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=Mv3h4vdJ0DY"
            },
            "content":{
                "5":"http://www.youtube.com/v/Mv3h4vdJ0DY?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r2---sn-4g57kuez.c.youtube.com/CigLENy73wIaHwk20En34uH9MhMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r2---sn-4g57kuez.c.youtube.com/CigLENy73wIaHwk20En34uH9MhMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":26,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"2",
            "ratingCount":2,
            "viewCount":290,
            "favoriteCount":0,
            "commentCount":0,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"L23YTl60oEg",
            "uploaded":"2013-12-16T14:25:46.000Z",
            "updated":"2014-02-10T18:34:13.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"ENTRENAMIENTO FUNCIONAL ESPECIAL PIERNA",
            "description":"Entrenamiento especializado en pierna, incluyendo grandes musculos, para una mayor quema de calorias.",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/L23YTl60oEg/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/L23YTl60oEg/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=L23YTl60oEg&feature=youtube_gdata_player"
            },
            "content":{
                "5":"http://www.youtube.com/v/L23YTl60oEg?version=3&f=user_uploads&app=youtube_gdata"
            },
            "duration":77,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"1",
            "ratingCount":1,
            "viewCount":394,
            "favoriteCount":0,
            "commentCount":4,
            "status":{
                "value":"restricted",
                "reason":"limitedSyndication"
            },
            "restrictions":[
            {
                "type":"country",
                "relationship":"deny",
                "countries":"FR"
            }
            ],
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"denied"
            }
        },
        {
            "id":"pUyGezSYbCU",
            "uploaded":"2013-10-21T19:49:14.000Z",
            "updated":"2014-03-07T12:23:20.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"entreno completo de pecho",
            "description":"Os dejo una de mis sesiones de pecho, de las que mas me gusta realizar, haz 10 repeticiones de cada ejercicio descansando entre series 1 minuto.",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/pUyGezSYbCU/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/pUyGezSYbCU/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=pUyGezSYbCU&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=pUyGezSYbCU"
            },
            "content":{
                "5":"http://www.youtube.com/v/pUyGezSYbCU?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r3---sn-4g57kued.c.youtube.com/CigLENy73wIaHwklbJg0e4ZMpRMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r3---sn-4g57kued.c.youtube.com/CigLENy73wIaHwklbJg0e4ZMpRMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":107,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"4",
            "ratingCount":4,
            "viewCount":1460,
            "favoriteCount":0,
            "commentCount":2,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"FSILuX3qQ1U",
            "uploaded":"2013-10-03T19:09:32.000Z",
            "updated":"2014-03-24T23:52:46.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"entrenamiento funcional juanjo martin",
            "description":"Es el entrenamieno definitivo de los amantes del fitness, trabajas en el mismo entrenamiento cardio, resistencia, fuerza, elasticidad, cordinacion, equilibrio y esta adaptado para todo tipo de persona y estado fisico.",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/FSILuX3qQ1U/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/FSILuX3qQ1U/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=FSILuX3qQ1U&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=FSILuX3qQ1U"
            },
            "content":{
                "5":"http://www.youtube.com/v/FSILuX3qQ1U?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r8---sn-4g57kuez.c.youtube.com/CigLENy73wIaHwlVQ-p9uQsiFRMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r8---sn-4g57kuez.c.youtube.com/CigLENy73wIaHwlVQ-p9uQsiFRMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":88,
            "aspectRatio":"widescreen",
            "rating":4.36,
            "likeCount":"21",
            "ratingCount":25,
            "viewCount":11519,
            "favoriteCount":0,
            "commentCount":8,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"ORdhEkfxVP8",
            "uploaded":"2013-09-28T22:17:54.000Z",
            "updated":"2014-03-11T19:31:22.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"entrenamiento TRX principiante",
            "description":"El entrenamiento con TRX es un entrenamiento que se trabaja con tu peso y la inclinación de tu cuerpo, se pueden hacer movimientos simples o entrenamientos funcionales.",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/ORdhEkfxVP8/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/ORdhEkfxVP8/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=ORdhEkfxVP8&feature=youtube_gdata_player",
                "mobile":"http://m.youtube.com/details?v=ORdhEkfxVP8"
            },
            "content":{
                "5":"http://www.youtube.com/v/ORdhEkfxVP8?version=3&f=user_uploads&app=youtube_gdata",
                "1":"rtsp://r2---sn-4g57kuez.c.youtube.com/CigLENy73wIaHwn_VPFHEmEXORMYDSANFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp",
                "6":"rtsp://r2---sn-4g57kuez.c.youtube.com/CigLENy73wIaHwn_VPFHEmEXORMYESARFEgGUgx1c2VyX3VwbG9hZHMM/0/0/0/video.3gp"
            },
            "duration":119,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"12",
            "ratingCount":12,
            "viewCount":2808,
            "favoriteCount":0,
            "commentCount":6,
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"allowed"
            }
        },
        {
            "id":"EPF4RvX4TFE",
            "uploaded":"2013-09-23T22:14:04.000Z",
            "updated":"2014-03-19T04:36:33.000Z",
            "uploader":"entrenosjuanjo",
            "category":"Sports",
            "title":"ENTRENAMIENTO VOLUMEN DE BICEPS Y TRICEPS",
            "description":"AQUI OS PRESENTO UN VIDEO DE UN ENTRENAMIENTO DE BICEPS Y TRICEPS.",
            "thumbnail":{
                "sqDefault":"http://i1.ytimg.com/vi/EPF4RvX4TFE/default.jpg",
                "hqDefault":"http://i1.ytimg.com/vi/EPF4RvX4TFE/hqdefault.jpg"
            },
            "player":{
                "default":"http://www.youtube.com/watch?v=EPF4RvX4TFE&feature=youtube_gdata_player"
            },
            "content":{
                "5":"http://www.youtube.com/v/EPF4RvX4TFE?version=3&f=user_uploads&app=youtube_gdata"
            },
            "duration":240,
            "aspectRatio":"widescreen",
            "rating":5.0,
            "likeCount":"3",
            "ratingCount":3,
            "viewCount":363,
            "favoriteCount":0,
            "commentCount":2,
            "status":{
                "value":"restricted",
                "reason":"limitedSyndication"
            },
            "accessControl":{
                "comment":"allowed",
                "commentVote":"allowed",
                "videoRespond":"moderated",
                "rate":"allowed",
                "embed":"allowed",
                "list":"allowed",
                "autoPlay":"allowed",
                "syndicate":"denied"
            }
        }
        ]
    }
}